# Generated by Django 5.1.1 on 2024-09-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('description', models.TextField(verbose_name='Описание')),
                ('link_img', models.TextField(verbose_name='Картинка')),
            ],
        ),
    ]
