# Generated by Django 5.1.1 on 2024-09-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoolGameShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
