# Generated by Django 5.1.1 on 2024-09-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoolGameShopApp', '0002_alter_game_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Games',
        ),
    ]
