# Generated by Django 5.1.1 on 2024-09-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoolGameShopApp', '0003_rename_game_games'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.AlterModelTable(
            name='game',
            table='test',
        ),
    ]
