# Generated by Django 5.1.1 on 2024-09-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoolGameShopApp', '0005_alter_game_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='game',
        ),
    ]
